name: CryptoCraft
main: net.ddns.vcccd.Main
version: 1.0.0
api-version: 1.20
depend: [Vault]
commands:
   test:
      description: Gives you the LaZerGun
      usage: /<command>
      permission: lazergun.give